import {useEffect, useState} from 'react';
import {ArrowUpRight, Check, Download, FileUp, FlaskConical, Loader2, Plus, ShieldCheck, Upload, X} from 'lucide-react';
import {api, classes, type Evaluation, type Job, type Model, type Recording, type Registry, type Replay, type TrainingRow} from './types';

export function Comparison({evaluation}:{evaluation:Evaluation}) {
  const rows:[string, keyof Evaluation['baseline']][]=[['Leak runs detected','detected_leak_runs'],['Leak runs missed','missed_leak_runs'],['Runs with false alarms','false_alarm_runs'],['Quiet non-leak runs','quiet_nonleak_runs'],[evaluation.candidate.location_evaluation_scope?.startsWith('Detected leak recordings')?'Location accuracy · detected leak runs':'Location window accuracy','location_accuracy'],['Median delay · detected runs','median_delay_seconds']];
  return <div className='comparison'><table><thead><tr><th>Untouched test set · {evaluation.candidate.recordings} recordings</th><th>Baseline</th><th>Candidate</th></tr></thead><tbody>{rows.map(([label,key])=><tr key={key}><td>{label}</td>{(['baseline','candidate'] as const).map(kind=><td key={kind}>{evaluation[kind][key]===null?'Not available':key==='location_accuracy'?`${(evaluation[kind][key]!*100).toFixed(1)}%`:key==='median_delay_seconds'?`${evaluation[kind][key]} s`:evaluation[kind][key]}</td>)}</tr>)}</tbody></table><p className='helper'>{evaluation.scope} Review false alarms and missed leaks before activating a candidate. This comparison does not establish plant readiness.</p></div>;
}

export function ImportDialog({mode,onClose,onTrain,registry,onModels,onReplay}:{mode:'model'|'replay';onClose:()=>void;onTrain:()=>void;registry:Registry;onModels:()=>Promise<void>;onReplay:(r:Replay)=>void}) {
  const [tab,setTab]=useState(mode),[files,setFiles]=useState<File[]>([]),[name,setName]=useState('Updated leak model'),[interval,setInterval]=useState(String(registry.versions.find(m=>m.id===registry.active)?.sample_interval||'')),[confirmed,setConfirmed]=useState(false),[locationOrder,setLocationOrder]=useState<string>((registry.versions.find(m=>m.id===registry.active)?.classes||classes).join(', ')),[modelId,setModelId]=useState(registry.active||registry.versions[0]?.id||''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState<Model|null>(null);
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[busy,onClose]);
  async function submit(){
    setBusy(true);setError('');
    try{
      if(tab==='model') {
        const body=new FormData();files.forEach(f=>body.append('files',f));body.append('name',name);body.append('sample_interval',interval);body.append('class_order_confirmed',String(confirmed));body.append('location_classes',JSON.stringify(locationOrder.split(',').map(c=>c.trim())));
        const m=await api<Model>('/models/import',{method:'POST',body});await onModels();setSuccess(m);
      }else{
        const body=new FormData();body.append('file',files[0]);body.append('model_id',modelId);
        const recording=await api<Recording>('/recordings',{method:'POST',body});
        const result=await api<Replay>(`/recordings/${recording.id}/replay?model_id=${encodeURIComponent(modelId)}`);
        onReplay(result);onClose();
      }
    }catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  async function selectImported(){if(!success)return;setBusy(true);try{await api(`/models/${success.id}/activate`,{method:'POST'});await onModels();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className='modal-backdrop' onClick={()=>{if(!busy)onClose();}}><section role='dialog' aria-modal='true' aria-labelledby='import-title' className='modal' onClick={e=>e.stopPropagation()}>
    <div className='modal-heading'><div><span className='eyebrow'>DATA & MODEL IMPORT</span><h2 id='import-title'>{success?'Model version validated':tab==='model'?'Import trained model':'Import sensor recording'}</h2></div><button aria-label='Close import' disabled={busy} onClick={onClose}><X size={20}/></button></div>
    {success?<><div className='success-panel'><ShieldCheck size={32}/><div><h3>{success.name}</h3><p>Validated {success.features.length} inputs, {success.time_steps}-reading windows and both model outputs. Your earlier versions are preserved.</p></div></div><p className='helper'>Selecting this version changes the model used for new imports and replays. A recording already on screen keeps its original predictions until you import it again.</p><div className='modal-actions'><button onClick={onClose}>Keep for later</button><button className='primary' disabled={busy} onClick={selectImported}>Select this model <ArrowUpRight size={16}/></button></div></>:<>
      <div className='import-tabs'><button className={tab==='model'?'active':''} onClick={()=>{setTab('model');setFiles([]);setError('');}}><Upload size={17}/>Update model</button><button className={tab==='replay'?'active':''} onClick={()=>{setTab('replay');setFiles([]);setError('');}}><FileUp size={17}/>Replay data</button><button onClick={onTrain}><FlaskConical size={17}/>Improve model</button></div>
      <p className='helper'>{tab==='model'?'Import trained weights to use them immediately, without training again. Choose the four notebook exports or a complete ZIP package.':'Upload a recorded sensor CSV. The selected model will score it using its saved preprocessing and window settings.'}</p>
      {tab==='model'?<><div className='form-grid'><label>Version name<input autoFocus value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label>Sensor interval · seconds<input type='number' min='.001' step='any' placeholder='Training data interval' value={interval} onChange={e=>setInterval(e.target.value)}/></label></div><div className='file-list'><code>lstm_leak_classifier.keras</code><code>lstm_leak_location.keras</code><code>scaler.pkl</code><code>config.pkl</code></div><div className='form-grid'><label>Locator format<select aria-label='Locator format' value={locationOrder.split(',').some(c=>c.trim()==='No leak')?'8':'7'} onChange={e=>{setLocationOrder((e.target.value==='7'?classes.slice(1):classes).join(', '));setConfirmed(false);}}><option value='8'>8 outputs · includes No leak</option><option value='7'>7 outputs · leak locations only (v2)</option></select></label><label>Exact output order<input aria-label='Locator output order' value={locationOrder} onChange={e=>{setLocationOrder(e.target.value);setConfirmed(false);}}/></label></div><label className='check-label'><input type='checkbox' checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I verified this output order against the model’s training labels.</span></label><p className='helper'>Version suffixes such as lstm_leak_location_v2.keras are accepted. Seven-output localization uses the first three recording clips after a confirmed alarm. Use the sensor interval and class order from training; these cannot be inferred from the weights. An exported package preserves its own interval and alarm policy. Standard notebook LSTM exports are supported; incompatible models get an explanation.</p></>:<label>Model for this replay<select value={modelId} onChange={e=>setModelId(e.target.value)}><option value='' disabled>Import a trained model first</option>{registry.versions.map(m=><option key={m.id} value={m.id}>{m.name}{m.id===registry.active?' · selected':''}</option>)}</select></label>}
      <label className='upload-zone'><FileUp size={30}/><strong>{files.length?`${files.length} file${files.length>1?'s':''} selected`:'Choose files to import'}</strong><span>{tab==='model'?'Four matching exports or one ZIP · up to 256 MB':'One UTF-8 sensor CSV · up to 25 MB'}</span><input aria-label='Choose import files' type='file' accept={tab==='model'?'.keras,.pkl,.zip':'.csv'} multiple={tab==='model'} onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>
      {files.length>0&&<p className='selected-files'>{files.map(f=>f.name).join(' · ')}</p>}
      {error&&<div role='alert' className='error'>{error}</div>}<div className='modal-actions'><button onClick={onClose} disabled={busy}>Cancel</button><button className='primary' disabled={busy||!files.length||(tab==='model'?(!name.trim()||!confirmed||Number(interval)<=0):!modelId)} onClick={submit}>{busy?<Loader2 className='spin' size={16}/>:<Upload size={16}/>} {busy?'Validating files…':tab==='model'?'Validate & import model':'Load scored replay'}</button></div>
    </>}
  </section></div>;
}

export default function ModelLab({registry,refresh,onImport}:{registry:Registry;refresh:()=>Promise<void>;onImport:()=>void}) {
  const [modelId,setModelId]=useState(registry.active||''),[rows,setRows]=useState<TrainingRow[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState('Fine-tuned candidate'),[epochs,setEpochs]=useState(5),[holdout,setHoldout]=useState(false),[job,setJob]=useState<Job|null>(null);
  useEffect(()=>{if(!modelId&&registry.active)setModelId(registry.active);},[registry.active,modelId]);
  useEffect(()=>{let stopped=false;void api<Job[]>('/training').then(jobs=>{if(!stopped)setJob(previous=>previous||jobs[0]||null);}).catch(()=>{});return()=>{stopped=true;};},[registry.versions.length]);
  useEffect(()=>{
    if(!job||!['queued','running'].includes(job.status))return;
    let stopped=false;
    const timer=window.setInterval(async()=>{try{const update=await api<Job>(`/training/${job.id}`);if(stopped)return;setJob(update);if(update.status==='complete')await refresh();}catch(e){if(!stopped)setError((e as Error).message);}},1500);
    return()=>{stopped=true;clearInterval(timer);};
  },[job?.id,job?.status,refresh]);
  const base=registry.versions.find(m=>m.id===modelId),running=!!job&&['queued','running'].includes(job.status);
  async function activate(id:string){setBusy(true);setError('');try{await api(`/models/${id}/activate`,{method:'POST'});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function add(files:FileList|null){if(!files||!modelId)return;setBusy(true);setError('');try{const additions:TrainingRow[]=[];for(const file of Array.from(files)){const body=new FormData();body.append('file',file);body.append('model_id',modelId);const r=await api<Recording>('/recordings',{method:'POST',body});additions.push({...r,group:file.name.replace(/\.csv$/i,''),split:'train',label:'No leak',onset:'',origin:'new'});}setRows(old=>[...old,...additions]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function edit(id:string,key:keyof TrainingRow,value:string){setRows(old=>old.map(r=>r.id===id?{...r,[key]:value,...(key==='label'&&value==='No leak'?{onset:''}:{})}:r));}
  async function start(){setBusy(true);setError('');try{const result=await api<Job>('/training',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model_id:modelId,name,epochs,independent_holdout_confirmed:holdout,rows:rows.map(({id,group,split,label,onset,origin})=>({id,group,split,label,origin,onset:onset===''?null:Number(onset)}))})});setJob(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className='lab-page'>
    <div className='page-heading'><div><span className='eyebrow'>MODEL MANAGEMENT</span><h1>Model management</h1><p>Import and select trained versions. Review fine-tuned candidates against the baseline.</p></div><button className='primary' onClick={onImport}><Upload size={17}/>Update model</button></div>
    {error&&<div className='error' role='alert'>{error}</div>}
    <div className='lab-columns'><section className='panel model-versions'><div className='panel-heading'><h2>Model versions</h2><span className='tag muted'>{registry.versions.length} stored</span></div>
      {registry.versions.length===0?<div className='empty-state'><ShieldCheck size={32}/><h3>Connect your trained model</h3><p>Import the detector, locator, scaler and configuration. You can replace the model later without rebuilding this dashboard.</p><button onClick={onImport}>Import first version <ArrowUpRight size={15}/></button></div>:<div className='version-list'>{[...registry.versions].reverse().map(m=><article key={m.id} className={m.id===registry.active?'version active-version':'version'}><div><span className='eyebrow'>{m.kind} · {new Date(m.created).toLocaleDateString()}</span><h3>{m.name}</h3><p>{m.features.length} sensors · {m.classes.length} location classes · {m.time_steps} readings/window · every {m.stride*m.sample_interval} s</p></div><div className='version-actions'>{registry.active===m.id?<span className='tag cyan'><Check size={12}/>Selected</span>:<button disabled={busy} onClick={()=>activate(m.id)}>Select version</button>}<a className='icon-button' aria-label={`Export ${m.name}`} title='Export complete model package' href={`/api/models/${m.id}/export`}><Download size={16}/></a></div>{m.parent_id&&<small>Fine-tuned from a preserved baseline</small>}{m.evaluation&&<details><summary>View saved evaluation</summary><Comparison evaluation={m.evaluation}/></details>}</article>)}</div>}
      <div className='model-note'><ShieldCheck size={17}/><p>Selection applies to future replays. Choose any stored version to roll back; uploaded packages persist across restarts.</p></div>
    </section><section className='panel training-panel'><div className='panel-heading'><div><h2>Improve current model</h2><p>Continue training from existing weights</p></div><FlaskConical size={21}/></div>
      <div className='form-grid'><label>Baseline to improve<select disabled={running||busy||!!rows.length} value={modelId} onChange={e=>{setModelId(e.target.value);setRows([]);}}><option value='' disabled>Select a trained model</option>{registry.versions.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Candidate name<input disabled={running} value={name} onChange={e=>setName(e.target.value)}/></label></div>
      <p className='helper'>Mix representative existing training data with new labeled recordings. Keep related scenarios in one group and assign groups before creating windows. Validation and test data must be independent of the baseline.</p>
      <div className='training-toolbar'><label className={`button ${!base||running||busy?'disabled':''}`}><Plus size={15}/>Add labeled CSVs<input type='file' accept='.csv' multiple disabled={!base||running||busy} onChange={e=>{void add(e.target.files);e.target.value='';}}/></label>{base&&<a className='text-link' href={`/api/models/${modelId}/template`}>Download sensor headers <Download size={12}/></a>}<span>{rows.length} recordings</span></div>
      {rows.length?<div className='training-table'><table><thead><tr><th>Recording / group</th><th>Label</th><th>Split</th><th>Origin</th><th>Verified onset (s)</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><span title={r.name}>{r.name}</span><input aria-label={`Group for ${r.name}`} value={r.group} disabled={running} onChange={e=>edit(r.id,'group',e.target.value)}/></td><td><select aria-label={`Label for ${r.name}`} value={r.label} disabled={running} onChange={e=>edit(r.id,'label',e.target.value)}>{classes.map(c=><option key={c}>{c}</option>)}</select></td><td><select aria-label={`Split for ${r.name}`} value={r.split} disabled={running} onChange={e=>edit(r.id,'split',e.target.value)}>{['train','validation','test'].map(s=><option key={s}>{s}</option>)}</select></td><td><select aria-label={`Origin for ${r.name}`} value={r.origin} disabled={running} onChange={e=>edit(r.id,'origin',e.target.value)}><option>new</option><option>existing</option></select></td><td><input aria-label={`Onset for ${r.name}`} type='number' step='any' placeholder='Optional' disabled={running||r.label==='No leak'} value={r.onset} onChange={e=>edit(r.id,'onset',e.target.value)}/></td><td><button aria-label={`Remove ${r.name}`} disabled={running} onClick={()=>setRows(old=>old.filter(x=>x.id!==r.id))}><X size={14}/></button></td></tr>)}</tbody></table></div>:<div className='training-empty'><FileUp size={22}/><p>{base?'Add independent recordings to prepare a training job.':'Import a complete model package to enable fine-tuning.'}</p></div>}
      {base&&base.classes.length===7&&<p className='helper'>V3 locator: only the first six clips of each leak recording train the location model. The detector uses all clips. Before-onset clips are excluded from location training; use recordings that start near the event.</p>}<p className='helper'>Each split needs a leak and a non-leak run. Leave onset blank when unverified; those files use whole-scenario labels and cannot establish detection delay.</p>
      <label className='check-label'><input type='checkbox' checked={holdout} disabled={running} onChange={e=>setHoldout(e.target.checked)}/><span>I confirm these validation and test groups were never used to train the baseline model.</span></label>
      <div className='training-footer'><label>Epoch limit<input type='number' min='1' max='20' value={epochs} disabled={running} onChange={e=>setEpochs(Number(e.target.value))}/></label><span className='helper'>Small updates · scaler preserved · early stopping</span><button className='primary' disabled={!base||rows.length<6||!holdout||busy||running||!name.trim()} onClick={start}>{busy||running?<Loader2 className='spin' size={16}/>:<FlaskConical size={16}/>} {running?'Training…':'Fine-tune candidate'}</button></div>
      {job&&<div className={`job-status ${job.status==='failed'?'job-failed':''}`}><div><strong>{job.phase}</strong><span>{Math.round(job.progress*100)}%</span></div><progress max='1' value={job.progress}/>{job.error&&<p className='error'>{job.error}</p>}{job.evaluation&&<><Comparison evaluation={job.evaluation}/><button className='primary' disabled={busy||registry.active===job.model_id} onClick={()=>activate(job.model_id!)}>{registry.active===job.model_id?'Candidate selected':'Select this candidate'}<ArrowUpRight size={15}/></button></>}</div>}
    </section></div>
  </div>;
}
